config/routes.rb
Rails.application.routes.draw do
  get 'welcome/hello'
  get 'login' => 'sessions#new'
  get 'signup'  => 'users#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users

  resources :articles do
    resources :comments
  end

  resources :searches

  root 'welcome#hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, :text, :author, presence: true, length: {minimum: 5}
  validates :category, presence: true

  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/search.rb
class Search < ApplicationRecord
  def search_articles
    articles=Article.all

    articles=articles.where(['author LIKE ?',"%#{author}%"]) if author.present?
    articles=articles.where(['category LIKE ?',category]) if category.present?
    articles=articles.where(['text LIKE ?',"%#{text}%"]) if text.present?

    return articles
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length:{minimum: 5}
  validates :password, presence: true, length:{minimum: 8}
  validates_uniqueness_of :username
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, except: [:index,:show]


  def index
    @articles = Article.search(params[:search])
  end

  def show
    @article=Article.find(params[:id])
  end

  def new
    @article=Article.new
  end

  def create
    @article=Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article=Article.find(params[:id])
  end

  def update
    @article=Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article=Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

end

private
  def article_params
    params.require(:article).permit(:title,:category,:text).merge(:author => @current_user.username)
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, only:[:create,:destroy]

  def create 
    @article=Article.find(params[:article_id])
    @comment=@article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article=Article.find(params[:article_id])
    @comment=@article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(:commenter => @current_user.username)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search=Search.new
    @categories=Article.distinct.pluck(:category)
  end

  def create
    @search=Search.create(search_params)
    redirect_to @search
  end

  def show
    @search=Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:author,:category,:text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def index
    redirect_to '/login'
  end

  def new
    if current_user
      redirect_to '/'
    end
  end

  def create
    @user=User.find_by(username: params[:sessions][:username])
    if @user && @user.authenticate(params[:sessions][:password])
      session[:user_id]=@user.id
      redirect_to '/'
    else
      render :new
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
     redirect_to '/'
    else
      @user=User.new
    end
  end

  def index
    redirect_to '/signup'
  end

  def create 
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to '/'
    else
      render :new
    end
  end

  private 
  def user_params
    params.require(:user).permit(:username,:password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
    @short_text="Welcome to this fantastic website!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.slim
=form_with model:@article, local:true do |form|
  -if @article.errors.any?
    div id="save_error"
      h2
        =pluralize(@article.errors.count,"error")
        | prohibited this article from being saved:
      ul
        -@article.errors.full_messages.each do |msg|
          li =msg

  p =form.label :title
  p =form.text_field :title
  p =form.label :category
  p
    =form.radio_button :category, "Food"
    |Food
    =form.radio_button :category, "Animals"
    |Animals
    =form.radio_button :category, "Football"
    |Football
    =form.radio_button :category, "News"
    |News
    =form.radio_button :category, "Tech"
    |Tech
    =form.radio_button :category, "Other"
    |Other

  p =form.label :text
  p =form.text_area :text
  p =form.submit

app/views/articles/_form.slim
=form_with model:@article, local:true do |form|
  -if @article.errors.any?
    div id="save_error"
      h2
        =pluralize(@article.errors.count,"error")
        | prohibited this article from being saved:
      ul
        -@article.errors.full_messages.each do |msg|
          li =msg

  p =form.label :title
  p =form.text_field :title
  p =form.label :category
  p
    =form.radio_button :category, "Food"
    |Food
    =form.radio_button :category, "Animals"
    |Animals
    =form.radio_button :category, "Football"
    |Football
    =form.radio_button :category, "News"
    |News
    =form.radio_button :category, "Tech"
    |Tech
    =form.radio_button :category, "Other"
    |Other

  p =form.label :text
  p =form.text_area :text
  p =form.submit

app/views/articles/edit.html.slim
h1 Edit Article
=render 'form'
p
  = link_to 'Back', articles_path

app/views/articles/edit.slim
h1 Edit Article
=render 'form'
p
  = link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles

p = form_tag articles_path,:method => 'get' do
 =text_field_tag :search, params[:search]
 =submit_tag "Search", name: nil

p = link_to 'Advanced Search', new_search_path

table
  tr
    th Title
    th Category
    th Text
    th Author

  - @articles.each do |article|
    tr
      td = article.title
      td = article.category
      td = article.text
      td = article.author
      td = link_to 'Show', article_path(article)
      -if current_user
        -if current_user.username==article.author
          td = link_to 'Edit', edit_article_path(article)
          td = link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}

p = link_to 'New Article', new_article_path

app/views/articles/index.slim
h1 Listing articles

p = form_tag articles_path,:method => 'get' do
 =text_field_tag :search, params[:search]
 =submit_tag "Search", name: nil

p = link_to 'Advanced Search', new_search_path

table
  tr
    th Title
    th Category
    th Text
    th Author

  - @articles.each do |article|
    tr
      td = article.title
      td = article.category
      td = article.text
      td = article.author
      td = link_to 'Show', article_path(article)
      -if current_user
        -if current_user.username==article.author
          td = link_to 'Edit', edit_article_path(article)
          td = link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}

p = link_to 'New Article', new_article_path

app/views/articles/new.slim
h1 New Article!
=render 'form'
p= link_to 'Back', articles_path

app/views/articles/show.html.slim
p
  strong Title:
  br
  = @article.title
p
  strong Category:
  br
  = @article.category
p
  strong Text:
  br
  = @article.text
p
  strong Author:
  br
  = @article.author
h2 Comments
=render @article.comments
h2 Add a comment:
=render 'comments/form'

- if current_user
  - if current_user.username==@article.author
    p =link_to 'Edit', edit_article_path(@article)
    p =link_to 'Delete', article_path(@article),method: :delete, data:{confirm: 'Are you sure?'}
p =link_to 'See all articles', articles_path

app/views/articles/show.slim
p
  strong Title:
  br
  = @article.title
p
  strong Category:
  br
  = @article.category
p
  strong Text:
  br
  = @article.text
p
  strong Author:
  br
  = @article.author
h2 Comments
=render @article.comments
h2 Add a comment:
=render 'comments/form'

- if current_user
  - if current_user.username==@article.author
    p =link_to 'Edit', edit_article_path(@article)
    p =link_to 'Delete', article_path(@article),method: :delete, data:{confirm: 'Are you sure?'}
p =link_to 'See all articles', articles_path

app/views/comments/_comment.html.slim
p
  strong Commenter:
  =comment.commenter
p
  strong Comment:
  =comment.body
-if current_user
   - if current_user.username==comment.commenter
      =link_to 'Delete Comment',[comment.article,comment],method: :delete, data: {confirm:'Are you sure?'}

app/views/comments/_comment.slim
p
  strong Commenter:
  =comment.commenter
p
  strong Comment:
  =comment.body
-if current_user
   - if current_user.username==comment.commenter
      =link_to 'Delete Comment',[comment.article,comment],method: :delete, data: {confirm:'Are you sure?'}

app/views/comments/_form.html.slim
=form_with(model:[@article,@article.comments.build],local:true) do |form|
  p
    =form.label :body
    br
    =form.text_area :body
  p =form.submit

app/views/comments/_form.slim
=form_with(model:[@article,@article.comments.build],local:true) do |form|
  p
    =form.label :body
    br
    =form.text_area :body
  p =form.submit

app/views/layouts/_navbar.slim
-if current_user
    li
      =current_user.username
    li
      =link_to 'Log out', logout_path, method:"delete"
-else
    li
      =link_to 'Log in', login_path
    li
      =link_to 'Sign up', signup_path

app/views/layouts/application.html.slim
doctype html
html
  head
    =csrf_meta_tags
    =csp_meta_tag
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    =javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, inicial-scale=1"
    script src='https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js' type='text/javascript'
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" type="text/javascript"
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"

    title Article Site
    
    .body
    =render 'layouts/navbar'
    ==yield

app/views/layouts/application.slim
doctype html
html
  head
    =csrf_meta_tags
    =csp_meta_tag
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    =javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, inicial-scale=1"

    title Article Site

    .body
    =render 'layouts/navbar'
    ==yield

app/views/searches/new.html.slim
h1 Advanced Search


=form_for @search do |f|
  p=f.label :author
  p=f.text_field :author

  p=f.label :category
  p=f.select :category, options_for_select(@categories), :include_blank =>true

  p=f.label :text
  p=f.text_field :text

  p=f.submit 'Search'

p= link_to 'Back', articles_path

app/views/searches/new.slim
h1 Advanced Search


=form_for @search do |f|
  p=f.label :author
  p=f.text_field :author

  p=f.label :category
  p=f.select :category, options_for_select(@categories), :include_blank =>true

  p=f.label :text
  p=f.text_field :text

  p=f.submit 'Search'

p= link_to 'Back', articles_path

app/views/searches/show.html.slim
h1 Search Results

-if @search.search_articles.empty?
  p Nothing Found

-else

table
  tr
    th Title
    th Category
    th Text
    th Author

  -@search.search_articles.each do |article|
   tr
     td = article.title
     td = article.category
     td = article.text
     td = article.author
     td = link_to 'Show', article_path(article)
     -if current_user
       -if current_user.username==article.author
         td = link_to 'Edit', edit_article_path(article)
         td = link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}

p=link_to 'Back', new_search_path

app/views/searches/show.slim
h1 Search Results

-if @search.search_articles.empty?
  p Nothing Found

-else

table
  tr
    th Title
    th Category
    th Text
    th Author

  -@search.search_articles.each do |article|
   tr
     td = article.title
     td = article.category
     td = article.text
     td = article.author
     td = link_to 'Show', article_path(article)
     -if current_user
       -if current_user.username==article.author
         td = link_to 'Edit', edit_article_path(article)
         td = link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}

p=link_to 'Back', new_search_path

app/views/users/new.html.slim
- if @user.errors.any?
  - @user.errors.full_messages.each do |msg|
    = msg
h2 Sign Up
=form_for(@user) do |form|
  p=form.text_field :username, :placeholder =>"Username"
  p=form.password_field :password, :placeholder =>"Password (min. 8 characters)"
  p=form.submit "Create an account", class: "btn-submit"

app/views/users/new.slim
- if @user.errors.any?
  - @user.errors.full_messages.each do |msg|
    = msg
h2 Sign Up
=form_for(@user) do |form|
  p=form.text_field :username, :placeholder =>"Username"
  p=form.password_field :password, :placeholder =>"Password (min. 8 characters)"
  p=form.submit "Create an account", class: "btn-submit"

app/views/welcome/hello.html.slim
h1 = @short_text
p= link_to 'Articles', controller: 'articles'